# Generated by Django 3.2.5 on 2021-10-25 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_last_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
